/* vi: set ts=4 expandtab shiftwidth=4: */
#ifndef _H_COM_DIAG_CODEX_PLATFORM_
#define _H_COM_DIAG_CODEX_PLATFORM_

/**
 * @file
 *
 * Copyright 2020-2025 Digital Aggregates Corporation, Colorado, USA.
 * Licensed under the terms in LICENSE.txt.
 *
 * The Codex Platform feature tries to determine what OpenSSL
 * implementation is being used. It does default to something
 * reasonable. But things work best if it can really tell, since
 * the API differs between implementations.
 */

/*******************************************************************************
 * PLATFORM
 ******************************************************************************/

#if defined(OPENSSL_VERSION_NUMBER) && (OPENSSL_VERSION_NUMBER == 0x1010006f) && !defined(OPENSSL_IS_BORINGSSL)
#   define COM_DIAG_CODEX_PLATFORM "OpenSSL 1.1.0"
#   define COM_DIAG_CODEX_PLATFORM_OPENSSL 0x1010006fL
#   define COM_DIAG_CODEX_PLATFORM_OPENSSL_1_1_0 1
#elif defined(OPENSSL_VERSION_NUMBER) && (OPENSSL_VERSION_NUMBER == 0x1000207f) && !defined(OPENSSL_IS_BORINGSSL)
#   define COM_DIAG_CODEX_PLATFORM "OpenSSL 1.0.2"
#   define COM_DIAG_CODEX_PLATFORM_OPENSSL 0x1000207fL
#   define COM_DIAG_CODEX_PLATFORM_OPENSSL_1_0_2 1
#elif defined(OPENSSL_VERSION_NUMBER) && (OPENSSL_VERSION_NUMBER == 0x1000114fL) && !defined(OPENSSL_IS_BORINGSSL)
#   define COM_DIAG_CODEX_PLATFORM "OpenSSL 1.0.1"
#   define COM_DIAG_CODEX_PLATFORM_OPENSSL 0x1000114fL
#   define COM_DIAG_CODEX_PLATFORM_OPENSSL_1_0_1 1
#elif defined(OPENSSL_VERSION_NUMBER) && (OPENSSL_VERSION_NUMBER == 0x1010100fL) && !defined(OPENSSL_IS_BORINGSSL)
#   define COM_DIAG_CODEX_PLATFORM "OpenSSL 1.1.1"
#   define COM_DIAG_CODEX_PLATFORM_OPENSSL 0x1010100fL
#   define COM_DIAG_CODEX_PLATFORM_OPENSSL_1_1_1 1
#elif defined(OPENSSL_VERSION_NUMBER) && (OPENSSL_VERSION_NUMBER == 0x10101002L) && !defined(OPENSSL_IS_BORINGSSL)
#   define COM_DIAG_CODEX_PLATFORM "OpenSSL 1.1.1"
#   define COM_DIAG_CODEX_PLATFORM_OPENSSL 0x10101002L
#   define COM_DIAG_CODEX_PLATFORM_OPENSSL_1_1_1 1
#elif defined(OPENSSL_VERSION_NUMBER) && (OPENSSL_VERSION_NUMBER == 0x1010102fL) && !defined(OPENSSL_IS_BORINGSSL)
#   define COM_DIAG_CODEX_PLATFORM "OpenSSL 1.1.1"
#   define COM_DIAG_CODEX_PLATFORM_OPENSSL 0x1010102fL
#   define COM_DIAG_CODEX_PLATFORM_OPENSSL_1_1_1 1
#elif defined(OPENSSL_VERSION_NUMBER) && (OPENSSL_VERSION_NUMBER == 0x1010104fL) && !defined(OPENSSL_IS_BORINGSSL)
#   define COM_DIAG_CODEX_PLATFORM "OpenSSL 1.1.1"
#   define COM_DIAG_CODEX_PLATFORM_OPENSSL 0x1010104fL
#   define COM_DIAG_CODEX_PLATFORM_OPENSSL_1_1_1 1
#elif defined(OPENSSL_VERSION_NUMBER) && (OPENSSL_VERSION_NUMBER == 0x1010106fL) && !defined(OPENSSL_IS_BORINGSSL)
#   define COM_DIAG_CODEX_PLATFORM "OpenSSL 1.1.1"
#   define COM_DIAG_CODEX_PLATFORM_OPENSSL 0x1010106fL
#   define COM_DIAG_CODEX_PLATFORM_OPENSSL_1_1_1 1
#elif defined(OPENSSL_VERSION_NUMBER) && (OPENSSL_VERSION_NUMBER == 0x101010efL) && !defined(OPENSSL_IS_BORINGSSL)
#   define COM_DIAG_CODEX_PLATFORM "OpenSSL 1.1.1n"
#   define COM_DIAG_CODEX_PLATFORM_OPENSSL 0x101010efL
#   define COM_DIAG_CODEX_PLATFORM_OPENSSL_1_1_1 1
#elif defined(OPENSSL_VERSION_NUMBER) && (OPENSSL_VERSION_NUMBER == 0x30000020L) && !defined(OPENSSL_IS_BORINGSSL)
#   define COM_DIAG_CODEX_PLATFORM "OpenSSL 3.0.2"
#   define COM_DIAG_CODEX_PLATFORM_OPENSSL 0x30000020L
#   define COM_DIAG_CODEX_PLATFORM_OPENSSL_3_0_2 1
#elif defined(OPENSSL_VERSION_NUMBER) && (OPENSSL_VERSION_NUMBER == 0x300000d0L) && !defined(OPENSSL_IS_BORINGSSL)
#   define COM_DIAG_CODEX_PLATFORM "OpenSSL 3.0.13"
#   define COM_DIAG_CODEX_PLATFORM_OPENSSL 0x300000d0L
#   define COM_DIAG_CODEX_PLATFORM_OPENSSL_3_0_13 1
#elif defined(OPENSSL_VERSION_NUMBER) && (OPENSSL_VERSION_NUMBER == 0x30300020L) && !defined(OPENSSL_IS_BORINGSSL)
#   define COM_DIAG_CODEX_PLATFORM "OpenSSL 3.3.2"
#   define COM_DIAG_CODEX_PLATFORM_OPENSSL 0x30300020L
#   define COM_DIAG_CODEX_PLATFORM_OPENSSL_3_3_2 1
#elif defined(OPENSSL_VERSION_NUMBER) && (OPENSSL_VERSION_NUMBER == 0x1010007fL) && defined(OPENSSL_IS_BORINGSSL)
#   define COM_DIAG_CODEX_PLATFORM "BoringSSL 1.1.0"
#   define COM_DIAG_CODEX_PLATFORM_BORINGSSL 0x1010007fL
#   define COM_DIAG_CODEX_PLATFORM_BORINGSSL_1_1_0 1
#elif defined(OPENSSL_IS_BORINGSSL)
#   warning Codex has not been tested against this BoringSSL version (assume 1.1.0)
#   define COM_DIAG_CODEX_PLATFORM "BoringSSL X.X.X"
#   define COM_DIAG_CODEX_PLATFORM_BORINGSSL 0x1010007fL
#   define COM_DIAG_CODEX_PLATFORM_BORINGSSL_1_1_0 1
#else
#   warning Codex has not been tested against this OpenSSL version (assume 3.3.2).
#   define COM_DIAG_CODEX_PLATFORM "OpenSSL X.X.X"
#   define COM_DIAG_CODEX_PLATFORM_OPENSSL 0x30300020L
#   define COM_DIAG_CODEX_PLATFORM_OPENSSL_3_3_2 1
#endif

#endif
